language: ruby
rvm:
- 2.4.2
notifications:
  slack:
    secure: blpydwVqac53dvFL0pBeM1bQsk+z69aTjdQc9tHxb9+tSCtlCsX3oPPI/oXNDuvxXvWj5/Acd79sCYX1ugqPqPR38/v6JgBh5zNeool/c8Eeitgz3f9XaEgQQU2lYiOT6sfFPEgc9zpQ2w96ZPUDSsh0L1RYNWp2xq+/cIl8YcdRumbotjuABbvOo10T3ZGzQXIcFRFc9R5FH9ZzGkugRtoviqND3Wl6jjnF5Kf3c+GFMgBT97tdK8oTrCgxkCTBZeGSp6MtKKtCRUNMzuwcsoaELHQotcYYIE/uW2J6ZLOcmH5mMhRGmKOGMw3ar7c4kFy9LVxjQ26Eg6Lq+3iM9nqgMIvBpe8oaHk7RZug1Ojv89wac2JEgrrrP2KTuebeZv32HPkJCjNAuFHUWp+GkkCI3Ju7MCRSQFP6OWMoMFDFQTuJg5taSL7vjSTSJa7Pw+Ymdh/8oCxeSA5PO5dPe0jU12eCZvut5jyTebusr1O2OZLErB1P1BgByQpT/JOVA+l0XyHLTdtRfaJAnK9LF4PHXlqPhhkw48WUPYM2IYA2s6DZp5yFVQLZYydtw7h9AByXkPqXkmvDOnO8SNYjseeGiAo2GBKTVC7fRNsYNcOhp370sjHdC9InffIsgAlT+n/ccrHRmzq28aMs/vOf36SpL1/Tub+jfJKFpbmiBNM=
